name = "sales-submission-worker"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[[d1_databases]]
binding = "DB"
database_name = "sales_tracking_db"
database_id = "da47669f-6f9f-4d9e-8970-618a7c1d5009"
